### ISSUE TITLE
schema permissions?

### ISSUE THREAD

**Issue by MichaelDBA** [cybertec-postgresql/pg_permissions#3]
The schema permissions view is this:
```
CREATE VIEW schema_permissions AS
SELECT obj_type 'SCHEMA' AS object_type,
       r.rolname AS role_name,
       n.nspname AS schema_name,
       NULL::text AS object_name,
       NULL::name AS column_name,
       p.perm::perm_type AS permission,
       has_schema_privilege(r.oid, n.oid, p.perm) AS granted
FROM pg_catalog.pg_namespace AS n
   CROSS JOIN pg_catalog.pg_roles AS r
   CROSS JOIN (VALUES ('USAGE'), ('CREATE')) AS p(perm)
WHERE n.nspname <> 'information_schema'
  AND n.nspname NOT LIKE 'pg_%'
  AND NOT r.rolsuper;
```
I do not see how this gets schema permissions since its doing a cartesian product with permissions, USAGE and CREATE?

Isn't the point of this view to get current schema permissions for non superuser roles?

**Comment by kovmir** [comment]
[`README.md`](https://github.com/cybertec-postgresql/pg_permissions#readme) mentions the purpose of `schema_permissions`.

**Comment by laurenz** [comment]
The view lists all possible schemas, permissions and roles.

To get the permissions that are granted, run something like

    SELECT * FROM schema_permissions WHERE granted;
