### ISSUE TITLE
Inconsistency in the names

### ISSUE THREAD

**Issue by devrimgunduz** [cybertec-postgresql/pg_permissions#4]
Hi,

Why it is sometimes pg_permission, and sometimes pg_permissions in the file names, or tarball name, project name, etc.?

Thanks!

**Comment by LorenzHenk** [comment]
Hey, thanks for noticing. We had a typo in the repository name. The correct name is `pg_permissions`.

**Comment by devrimgunduz** [comment]
Hi,

Can you please update README.md as well?

README.md: [issue]: https://github.com/cybertec-postgresql/pg_permission/issues

**Comment by laurenz** [comment]
Thanks for the report, I fixed that in 5b3e79e9514d93f7e4d173ae6543b4cca389a811.
