### ISSUE TITLE
Grants through roles

### ISSUE THREAD

**Issue by pmpetit** [cybertec-postgresql/pg_permissions#5]
Hello,
in this context,
MY_SCHEMA with MY_TABLE inside.
i create 2 roles:
R_MY_SCHEMA => grant select on my_table to r_my_schema
W_MY_SCHEMA => grant all on my_table to w_my_schema

if i create a user my_user with
grant w_my_schema to my_user.

then how do you think i can deal with pg_permissions ?
thanks

**Comment by laurenz** [comment]
Just like the documentation says.
